### PR TITLE
wire bug fixes and improvements

### LINKED ISSUE #26: wires not visually connected to connector
Maybe just solve this quickly by setting position every frame.

### LINKED ISSUE #28: connectors become kinematic after vr disconnect
maybe we want this to be the only method of disconnecting, actually grabbing the connector, the automatic conflict disconnection might not even be wanted

### LINKED ISSUE #34: wires fly away when root object moves
Things probably need to work according to the local position of the root object, or purely in world space, to not break

### LINKED ISSUE #35: wire collisions

### PR DESCRIPTION
**Pull request by steenish**
Connected issues that should be solved now:
 * closes #34 
 * closes #28 
 * closes #26 
 * closes #35 

This should really be tested in VR

### CODE REVIEW

File: Connected/Assets/Scripts/WirePhysics.cs [hunk 1]
```diff
@@ -113,31 +112,55 @@ private class Stick {
...
+			}
+
+			// Look for collisions from gravity force.
+			shuffledIndices = Enumerable.Range(0, points.Length).ToList().OrderBy(e => Random.value);
+			foreach (int index in shuffledIndices) {
+				Point p = points[index];
+				if (!p.locked) {
+					Vector3 positionBeforeUpdate = p.position;
+
+					Ray collisionRay = new Ray(p.position, Physics.gravity);
```
Comment (raaavioli) [inline Connected/Assets/Scripts/WirePhysics.cs:151]: Does this do anything?

Comment (raaavioli) [inline Connected/Assets/Scripts/WirePhysics.cs:151]: This variable seems to be unused.

File: Connected/Assets/Scripts/Components/Wire/WirePhysics.cs [hunk 2]
```diff
@@ -123,29 +124,51 @@ private class Stick {
...
+				}
+			}
+
+			// Look for collisions from gravity force.
+			shuffledIndices = Enumerable.Range(0, points.Length).ToList().OrderBy(e => Random.value);
+			foreach (int index in shuffledIndices) {
+				Point p = points[index];
+				if (!p.locked) {
+					Vector3 positionBeforeUpdate = p.position;
+
```
Comment (raaavioli) [inline Connected/Assets/Scripts/Components/Wire/WirePhysics.cs:150]: Is "collisionRay" supposed to be used?

**Review by raaavioli — DISMISSED** [review]

File: Connected/Assets/Scripts/WirePhysics.cs [hunk 3]
```diff
@@ -113,31 +112,55 @@ private class Stick {
...
+				}
+			}
+
+			// Look for collisions from gravity force.
+			shuffledIndices = Enumerable.Range(0, points.Length).ToList().OrderBy(e => Random.value);
+			foreach (int index in shuffledIndices) {
+				Point p = points[index];
+				if (!p.locked) {
+					Vector3 positionBeforeUpdate = p.position;
+
```
Comment (raaavioli) [inline Connected/Assets/Scripts/WirePhysics.cs:150]: This variable seems to be unused. Remove if you want, otherwise it's not really a problem

I hate github's comment system.  When adding a single comment, the selected line seems to not be included and a few lines below will be, but when reviewing the selected line will be included and a few lines above..?

File: Connected/Assets/Scripts/WirePhysics.cs (hunk 1 above)
Comment (raaavioli) [inline Connected/Assets/Scripts/WirePhysics.cs]: Is "collisionRay" unused? Not really a problem in that case. Remove if you want.

File: Connected/Assets/Scripts/Components/Wire/Wire.cs [hunk 4]
```diff
@@ -19,9 +19,9 @@ public class Wire : MonoBehaviour {
 	}
 
 	private void Update() {
-		if (positive == null || negative == null) {
-			wireRenderer.connected = false;
-		}
+		//if (positive == null || negative == null) {
```
Comment (raaavioli) [inline Connected/Assets/Scripts/Components/Wire/Wire.cs]: Are these commented out lines intended?

**Review by raaavioli — DISMISSED** [review]

**Review by raaavioli — DISMISSED** [review]
Lgtm!

**Review by raaavioli — APPROVED** [review]
